export interface CountryCode { code: string; dial: string; name: string; flag: string }

export const COUNTRY_CODES: CountryCode[] = [
  { code: 'IN', dial: '91', name: 'India', flag: '🇮🇳' },
  { code: 'US', dial: '1', name: 'United States', flag: '🇺🇸' },
  { code: 'CA', dial: '1', name: 'Canada', flag: '🇨🇦' },
  { code: 'GB', dial: '44', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'AE', dial: '971', name: 'United Arab Emirates', flag: '🇦🇪' },
  { code: 'SA', dial: '966', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'QA', dial: '974', name: 'Qatar', flag: '🇶🇦' },
  { code: 'KW', dial: '965', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'OM', dial: '968', name: 'Oman', flag: '🇴🇲' },
  { code: 'BH', dial: '973', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'SG', dial: '65', name: 'Singapore', flag: '🇸🇬' },
  { code: 'MY', dial: '60', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'ID', dial: '62', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', dial: '63', name: 'Philippines', flag: '🇵🇭' },
  { code: 'TH', dial: '66', name: 'Thailand', flag: '🇹🇭' },
  { code: 'VN', dial: '84', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'LK', dial: '94', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'BD', dial: '880', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'PK', dial: '92', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'NP', dial: '977', name: 'Nepal', flag: '🇳🇵' },
  { code: 'AU', dial: '61', name: 'Australia', flag: '🇦🇺' },
  { code: 'NZ', dial: '64', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'DE', dial: '49', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', dial: '33', name: 'France', flag: '🇫🇷' },
  { code: 'ES', dial: '34', name: 'Spain', flag: '🇪🇸' },
  { code: 'IT', dial: '39', name: 'Italy', flag: '🇮🇹' },
  { code: 'PT', dial: '351', name: 'Portugal', flag: '🇵🇹' },
  { code: 'NL', dial: '31', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'BE', dial: '32', name: 'Belgium', flag: '🇧🇪' },
  { code: 'CH', dial: '41', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'AT', dial: '43', name: 'Austria', flag: '🇦🇹' },
  { code: 'SE', dial: '46', name: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', dial: '47', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', dial: '45', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', dial: '358', name: 'Finland', flag: '🇫🇮' },
  { code: 'IE', dial: '353', name: 'Ireland', flag: '🇮🇪' },
  { code: 'PL', dial: '48', name: 'Poland', flag: '🇵🇱' },
  { code: 'RO', dial: '40', name: 'Romania', flag: '🇷🇴' },
  { code: 'GR', dial: '30', name: 'Greece', flag: '🇬🇷' },
  { code: 'TR', dial: '90', name: 'Türkiye', flag: '🇹🇷' },
  { code: 'RU', dial: '7', name: 'Russia', flag: '🇷🇺' },
  { code: 'UA', dial: '380', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'IL', dial: '972', name: 'Israel', flag: '🇮🇱' },
  { code: 'EG', dial: '20', name: 'Egypt', flag: '🇪🇬' },
  { code: 'ZA', dial: '27', name: 'South Africa', flag: '🇿🇦' },
  { code: 'NG', dial: '234', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'KE', dial: '254', name: 'Kenya', flag: '🇰🇪' },
  { code: 'GH', dial: '233', name: 'Ghana', flag: '🇬🇭' },
  { code: 'TZ', dial: '255', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'MA', dial: '212', name: 'Morocco', flag: '🇲🇦' },
  { code: 'BR', dial: '55', name: 'Brazil', flag: '🇧🇷' },
  { code: 'MX', dial: '52', name: 'Mexico', flag: '🇲🇽' },
  { code: 'AR', dial: '54', name: 'Argentina', flag: '🇦🇷' },
  { code: 'CL', dial: '56', name: 'Chile', flag: '🇨🇱' },
  { code: 'CO', dial: '57', name: 'Colombia', flag: '🇨🇴' },
  { code: 'PE', dial: '51', name: 'Peru', flag: '🇵🇪' },
  { code: 'CN', dial: '86', name: 'China', flag: '🇨🇳' },
  { code: 'HK', dial: '852', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'JP', dial: '81', name: 'Japan', flag: '🇯🇵' },
  { code: 'KR', dial: '82', name: 'South Korea', flag: '🇰🇷' },
  { code: 'TW', dial: '886', name: 'Taiwan', flag: '🇹🇼' },
];
