// Canonical WhatsApp Flow JSON for TN45 Travel Aid — v7.3
// Includes booking_for / passenger_name / passenger_phone (someone-else routing)
export const TN45_FLOW_JSON = {
  version: '7.3',
  screens: [
    {
      id: 'SERVICE_MENU',
      title: 'TN45 Travel Aid',
      terminal: false,
      data: {},
      layout: {
        type: 'SingleColumnLayout',
        children: [
          { type: 'TextHeading', text: '🤝 வணக்கம்! Welcome to TN 45 Travel!' },
          { type: 'TextBody', text: 'நாங்கள் உங்களுக்கு சிறந்த சேவை வழங்க தயாராக உள்ளோம்.\nWe are ready to serve you!' },
          { type: 'TextSubheading', text: 'சேவையை தேர்வு செய்யுங்கள் / Select a service' },
          {
            type: 'Form',
            name: 'service_form',
            children: [
              {
                type: 'RadioButtonsGroup',
                name: 'service',
                label: 'Train · Bus · Flight / ரயில் · பேருந்து · விமானம்',
                required: true,
                'data-source': [
                  { id: 'terminal-railbus', title: 'In Railway/Bus Station Assist — ₹200', description: 'பேருந்து / ரயில் நிலையம் உதவி · for 1 hour' },
                  { id: 'home-railbus', title: 'Home to seat (Railway/Bus) — ₹200', description: 'வீட்டிலிருந்து ரயில்/பேருந்து நிலையம்' },
                  { id: 'railbus-home', title: 'Railway/Bus Station to Home — ₹200', description: 'ரயில்/பேருந்து நிலையத்திலிருந்து வீடு' },
                  { id: 'festivity-half', title: 'Festivity Half Day (6H) — ₹600', description: 'விழா பயணம் உதவி அரை நாள்' },
                  { id: 'festivity-full', title: 'Festivity Full Day (12H) — ₹1200', description: 'விழா பயணம் உதவி முழு நாள்' },
                  { id: 'hospital', title: 'Hospital Visit Assist (4H) — ₹500', description: 'மருத்துவமனை உதவி · Pickup, OPD, drop' },
                  { id: 'outstation', title: 'Outstation Medical Escort — ₹1200/day', description: 'வெளியூர் மருத்துவ துணை · per day' },
                ],
              },
              { type: 'TextCaption', text: '➕ Add-ons: ♿ Wheelchair +₹50 \n 🧳 Porter (actual charges) \n🌙 After-hours (Night 10 PM to 6 AM) +20% extra \n💳 Advance: ₹200 via secure payment link · Balance to be paid at the end of the service.' },
              {
                type: 'Footer',
                label: 'Continue / தொடரவும்',
                'on-click-action': {
                  name: 'navigate',
                  next: { type: 'screen', name: 'BOOKING_FORM' },
                  payload: { service: '${form.service}' },
                },
              },
            ],
          },
        ],
      },
    },
    {
      id: 'BOOKING_FORM',
      title: 'Fill Reporting Details',
      terminal: false,
      data: { service: { type: 'string', __example__: 'terminal-railbus' } },
      layout: {
        type: 'SingleColumnLayout',
        children: [
          { type: 'TextHeading', text: '📋 Fill Reporting Details' },
          { type: 'TextCaption', text: 'விவரங்களை நிரப்பவும்' },
          {
            type: 'Form',
            name: 'booking_form',
            children: [
              { type: 'TextInput', name: 'name', label: 'Name / பெயர்', 'input-type': 'text', required: true, 'helper-text': 'Your full name / உங்கள் பெயர்' },
              { type: 'TextInput', name: 'phone', label: 'Phone / தொலைபேசி', 'input-type': 'phone', required: true, 'helper-text': '+91 96554 51299' },
              {
                type: 'RadioButtonsGroup',
                name: 'booking_for',
                label: 'Booking For / யாருக்காக?',
                required: true,
                'data-source': [
                  { id: 'myself', title: '👤 Myself / என்னுக்காக' },
                  { id: 'someone_else', title: '👥 Someone Else / வேறு ஒருவருக்காக' },
                ],
              },
              { type: 'TextInput', name: 'passenger_name', label: 'Passenger Name / பயணி பெயர்', 'input-type': 'text', required: false, 'helper-text': 'Full name of the actual traveller' },
              { type: 'TextInput', name: 'passenger_phone', label: 'Passenger Phone / பயணி தொலைபேசி', 'input-type': 'phone', required: false, 'helper-text': 'Direct number to reach the traveller' },
              {
                type: 'Dropdown', name: 'transport_mode', label: 'Transport Mode / பயண வகை', required: true,
                'data-source': [
                  { id: 'train', title: 'Train / ரயில்' },
                  { id: 'bus', title: 'Bus / பேருந்து' },
                  { id: 'flight', title: 'Flight / விமானம்' },
                  { id: 'private', title: 'Private Vehicle / சொந்த வாகனம்' },
                ],
              },
              {
                type: 'Dropdown', name: 'transport_details', label: 'Select Service Category / சேவை வகை தேர்வு', required: true,
                'data-source': [
                  { id: 'pickup', title: '🚖 Pick-up (Seat to Home)' },
                  { id: 'dropoff', title: '🚗 Drop-off (Home to Seat)' },
                  { id: 'medical-trip', title: '🏥 Medical Trip — Hospital Visit' },
                  { id: 'festival', title: '🎉 Festival Trip' },
                  { id: 'os-medical', title: '🏨 OS Medical — Outstation Hospital' },
                ],
              },
              { type: 'TextInput', name: 'service_info', label: 'Service Info / சேவை விவரம்', 'input-type': 'text', required: true, 'helper-text': 'Bus No. / Train No. / Hospital Name / Festival Location / OS Hospital Name' },
              { type: 'TextArea', name: 'address', label: 'Reporting Address / இடம்', required: true, 'helper-text': 'Full address / முழு முகவரி' },
              { type: 'TextInput', name: 'landmark', label: 'Nearest Landmark / அடையாளம்', required: true, 'helper-text': 'Eg: Near Central Bus Stand' },
              { type: 'DatePicker', name: 'date', label: 'Date of Service / தேதி', required: true },
              { type: 'TextInput', name: 'time', label: 'Reporting Time / நேரம்', 'input-type': 'text', required: true, 'helper-text': 'Eg: 09:30 AM' },
              { type: 'TextInput', name: 'hours', label: 'Expected Hrs/Days of Helper Service / உதவியாளர் சேவை நேரம்', 'input-type': 'text', required: true, 'helper-text': 'Flight 6E204 Arrival 09:25 AM | Train 12637 Arrival 06:40 AM | Bus Departure 08:00 PM | OS: No. of Days' },
              {
                type: 'CheckboxGroup', name: 'addons', label: '♿ Special Arrangement / சிறப்பு ஏற்பாடு', required: false,
                'data-source': [
                  { id: 'wheelchair', title: '♿ Wheelchair +₹50' },
                  { id: 'battery', title: '🔋 Battery Car (Actual charges)' },
                  { id: 'porter', title: '🧳 Porter (Actual charges)' },
                ],
              },
              { type: 'TextCaption', text: '💰 Base fare shown on service · Extra hours +₹100/hr · After-hours (after 10 PM) +20% extra' },
              {
                type: 'Footer', label: 'Review Booking → சரிபார்',
                'on-click-action': {
                  name: 'navigate',
                  next: { type: 'screen', name: 'REVIEW_BOOKING' },
                  payload: {
                    service: '${data.service}', name: '${form.name}', phone: '${form.phone}',
                    transport_mode: '${form.transport_mode}', transport_details: '${form.transport_details}',
                    service_info: '${form.service_info}', address: '${form.address}', landmark: '${form.landmark}',
                    date: '${form.date}', time: '${form.time}', hours: '${form.hours}', addons: '${form.addons}',
                    booking_for: '${form.booking_for}', passenger_name: '${form.passenger_name}', passenger_phone: '${form.passenger_phone}',
                  },
                },
              },
            ],
          },
        ],
      },
    },
    {
      id: 'REVIEW_BOOKING',
      title: 'Review Your Booking',
      terminal: false,
      data: {
        service: { type: 'string', __example__: 'hospital' },
        name: { type: 'string', __example__: 'Rajesh Kumar' },
        phone: { type: 'string', __example__: '+91 9XXXXXXXXX' },
        transport_mode: { type: 'string', __example__: 'train' },
        transport_details: { type: 'string', __example__: 'medical-trip' },
        service_info: { type: 'string', __example__: 'Rajaji Hospital, Madurai' },
        address: { type: 'string', __example__: '12, Anna Nagar, Trichy' },
        landmark: { type: 'string', __example__: 'Near Bus Stand' },
        date: { type: 'string', __example__: '2026-07-05' },
        time: { type: 'string', __example__: '09:30 AM' },
        hours: { type: 'string', __example__: '4' },
        addons: { type: 'array', items: { type: 'string' }, __example__: [] },
        booking_for: { type: 'string', __example__: 'myself' },
        passenger_name: { type: 'string', __example__: '' },
        passenger_phone: { type: 'string', __example__: '' },
      },
      layout: {
        type: 'SingleColumnLayout',
        children: [
          { type: 'TextHeading', text: 'Review Your Booking' },
          { type: 'TextCaption', text: 'பதிவை சரிபார்க்கவும் · Verify before confirming' },
          { type: 'TextSubheading', text: 'Service / சேவை' }, { type: 'TextBody', text: '${data.service}' },
          { type: 'TextSubheading', text: 'Name / பெயர்' }, { type: 'TextBody', text: '${data.name}' },
          { type: 'TextSubheading', text: 'Phone / தொலைபேசி' }, { type: 'TextBody', text: '${data.phone}' },
          { type: 'TextSubheading', text: 'Booking For / யாருக்காக' }, { type: 'TextBody', text: '${data.booking_for}' },
          { type: 'TextSubheading', text: 'Passenger Name / பயணி பெயர்' }, { type: 'TextBody', text: '${data.passenger_name}' },
          { type: 'TextSubheading', text: 'Passenger Phone / பயணி தொலைபேசி' }, { type: 'TextBody', text: '${data.passenger_phone}' },
          { type: 'TextSubheading', text: 'Transport Mode / பயண வகை' }, { type: 'TextBody', text: '${data.transport_mode}' },
          { type: 'TextSubheading', text: 'Service Category / சேவை வகை' }, { type: 'TextBody', text: '${data.transport_details}' },
          { type: 'TextSubheading', text: 'Service Info / சேவை விவரம்' }, { type: 'TextBody', text: '${data.service_info}' },
          { type: 'TextSubheading', text: 'Address / இடம்' }, { type: 'TextBody', text: '${data.address}' },
          { type: 'TextSubheading', text: 'Nearest Landmark / அடையாளம்' }, { type: 'TextBody', text: '${data.landmark}' },
          { type: 'TextSubheading', text: 'Date / தேதி' }, { type: 'TextBody', text: '${data.date}' },
          { type: 'TextSubheading', text: 'Time / நேரம்' }, { type: 'TextBody', text: '${data.time}' },
          { type: 'TextSubheading', text: 'Expected Hours / Days' }, { type: 'TextBody', text: '${data.hours}' },
          { type: 'TextCaption', text: 'Final fare calculated after service.\nAdvance ₹200 · Balance to be paid at the end of service.' },
          {
            type: 'Form', name: 'review_form',
            children: [{
              type: 'Footer', label: 'Confirm Booking →',
              'on-click-action': {
                name: 'navigate', next: { type: 'screen', name: 'BOOKING_CONFIRMED' },
                payload: {
                  service: '${data.service}', name: '${data.name}', phone: '${data.phone}',
                  transport_mode: '${data.transport_mode}', transport_details: '${data.transport_details}',
                  service_info: '${data.service_info}', address: '${data.address}', landmark: '${data.landmark}',
                  date: '${data.date}', time: '${data.time}', hours: '${data.hours}', addons: '${data.addons}',
                  booking_for: '${data.booking_for}', passenger_name: '${data.passenger_name}', passenger_phone: '${data.passenger_phone}',
                },
              },
            }],
          },
          {
            type: 'EmbeddedLink', text: '✏️ Edit Details / திருத்து',
            'on-click-action': {
              name: 'navigate', next: { type: 'screen', name: 'BOOKING_FORM' },
              payload: { service: '${data.service}' },
            },
          },
        ],
      },
    },
    {
      id: 'BOOKING_CONFIRMED',
      title: 'Booking Submitted',
      terminal: true,
      success: true,
      data: {
        service: { type: 'string', __example__: 'hospital' },
        name: { type: 'string', __example__: 'Rajesh Kumar' },
        phone: { type: 'string', __example__: '+91 9XXXXXXXXX' },
        transport_mode: { type: 'string', __example__: 'train' },
        transport_details: { type: 'string', __example__: 'medical-trip' },
        service_info: { type: 'string', __example__: 'Rajaji Hospital, Madurai' },
        address: { type: 'string', __example__: '12, Anna Nagar, Trichy' },
        landmark: { type: 'string', __example__: 'Near Bus Stand' },
        date: { type: 'string', __example__: '2026-07-05' },
        time: { type: 'string', __example__: '09:30 AM' },
        hours: { type: 'string', __example__: '4' },
        addons: { type: 'array', items: { type: 'string' }, __example__: [] },
        booking_for: { type: 'string', __example__: 'myself' },
        passenger_name: { type: 'string', __example__: '' },
        passenger_phone: { type: 'string', __example__: '' },
      },
      layout: {
        type: 'SingleColumnLayout',
        children: [
          { type: 'TextHeading', text: '✅ Booking Submitted!' },
          { type: 'TextCaption', text: 'பதிவு பெறப்பட்டது!' },
          { type: 'TextBody', text: '━━━━━━━━━━━━━' },
          { type: 'TextSubheading', text: 'Service / சேவை' }, { type: 'TextBody', text: '${data.service}' },
          { type: 'TextSubheading', text: 'Name / பெயர்' }, { type: 'TextBody', text: '${data.name}' },
          { type: 'TextSubheading', text: 'Phone / தொலைபேசி' }, { type: 'TextBody', text: '${data.phone}' },
          { type: 'TextSubheading', text: 'Booking For / யாருக்காக' }, { type: 'TextBody', text: '${data.booking_for}' },
          { type: 'TextSubheading', text: 'Passenger Name / பயணி பெயர்' }, { type: 'TextBody', text: '${data.passenger_name}' },
          { type: 'TextSubheading', text: 'Passenger Phone / பயணி தொலைபேசி' }, { type: 'TextBody', text: '${data.passenger_phone}' },
          { type: 'TextSubheading', text: 'Date & Time' }, { type: 'TextBody', text: '${data.date}' }, { type: 'TextBody', text: '${data.time}' },
          { type: 'TextSubheading', text: 'Transport / சேவை விவரம்' }, { type: 'TextBody', text: '${data.transport_mode}' }, { type: 'TextBody', text: '${data.service_info}' },
          { type: 'TextSubheading', text: 'Address / இடம்' }, { type: 'TextBody', text: '${data.address}' },
          { type: 'TextSubheading', text: 'Nearest Landmark' }, { type: 'TextBody', text: '${data.landmark}' },
          { type: 'TextSubheading', text: 'Expected Hours / Days' }, { type: 'TextBody', text: '${data.hours}' },
          { type: 'TextBody', text: '━━━━━━━━━━━━━' },
          { type: 'TextSubheading', text: '💳 Next Step: Pay Advance ₹200' },
          { type: 'TextBody', text: 'A secure Razorpay payment link for ₹200 will arrive on this WhatsApp chat in a few seconds.' },
          { type: 'TextBody', text: 'Pay via UPI, card, or net banking. Remaining balance is paid to the helper after service.' },
          { type: 'TextBody', text: '━━━━━━━━━━━━━' },
          { type: 'TextSubheading', text: '🧑‍✈️ Helper / உதவியாளர்' },
          { type: 'TextBody', text: 'Helper will be assigned 1 hour before service.\nஉதவியாளர் 1 மணி நேரம் முன்பு நியமிக்கப்படுவார்.' },
          { type: 'TextBody', text: '━━━━━━━━━━━━━' },
          { type: 'TextCaption', text: '⚠️ Bypassing helpers will lead to block of customer ID.' },
          { type: 'TextCaption', text: '🔒 All communication through TN45 only.' },
          {
            type: 'Form', name: 'confirmed_form',
            children: [{
              type: 'Footer', label: '💳 Proceed to Payment →',
              'on-click-action': {
                name: 'complete',
                payload: {
                  status: 'submitted',
                  service: '${data.service}', name: '${data.name}', phone: '${data.phone}',
                  transport_mode: '${data.transport_mode}', transport_details: '${data.transport_details}',
                  service_info: '${data.service_info}', address: '${data.address}', landmark: '${data.landmark}',
                  date: '${data.date}', time: '${data.time}', hours: '${data.hours}', addons: '${data.addons}',
                  booking_for: '${data.booking_for}', passenger_name: '${data.passenger_name}', passenger_phone: '${data.passenger_phone}',
                },
              },
            }],
          },
        ],
      },
    },
  ],
} as const;
