project_id = "jpenkubzwugozbibtnqd"

[functions.whatsapp-webhook]
verify_jwt = false

[functions.chatbot-message]
verify_jwt = false

[functions.widget-js]
verify_jwt = false

[functions.generic-webhook]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.razorpay-record-webhook]
verify_jwt = false
